version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  scraper:
    build: ./scraper/
    depends_on:
      - db
  web:
    build: ./webapp/
    ports:
      - 8080:8080